'use client'
import { Button } from '@/components/ui/button'
import { Download } from 'lucide-react'

export function DownloadSummaryButton({
  title,
  summaryText,
  fileName,
  createdAt,
}: {
  title: string
  summaryText: string
  fileName: string
  createdAt: string
}) {
  const handleDownload = () => {
    const summaryContent = `Title: ${title}\nGenerated on: ${new Date(
      createdAt,
    ).toLocaleDateString()}\nOriginal File:  ${fileName}\nGenerated by Sommaire\n\n${summaryText}
    `
    const blob = new Blob([summaryContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')

    link.href = url
    link.download = `SOMMAIRE-${title.replace(/[^a-z0-9]/gi, '_')}.txt`
    document.body.appendChild(link)
    link.click()

    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  return (
    <Button
      size='sm'
      variant='default'
      className='bg-transparent text-cyan-600 hover:bg-cyan-600 hover:text-white'
      onClick={handleDownload}
    >
      <Download className='h-4 w-4' />
      <span className='hidden sm:inline'>
        Download <span className='hidden md:inline'>Summary</span>
      </span>
    </Button>
  )
}
